// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/solo-io/valet/cli/internal/ensure/client (interfaces: AwsDnsClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockAwsDnsClient is a mock of AwsDnsClient interface
type MockAwsDnsClient struct {
	ctrl     *gomock.Controller
	recorder *MockAwsDnsClientMockRecorder
}

// MockAwsDnsClientMockRecorder is the mock recorder for MockAwsDnsClient
type MockAwsDnsClientMockRecorder struct {
	mock *MockAwsDnsClient
}

// NewMockAwsDnsClient creates a new mock instance
func NewMockAwsDnsClient(ctrl *gomock.Controller) *MockAwsDnsClient {
	mock := &MockAwsDnsClient{ctrl: ctrl}
	mock.recorder = &MockAwsDnsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAwsDnsClient) EXPECT() *MockAwsDnsClientMockRecorder {
	return m.recorder
}

// CreateMapping mocks base method
func (m *MockAwsDnsClient) CreateMapping(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMapping", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMapping indicates an expected call of CreateMapping
func (mr *MockAwsDnsClientMockRecorder) CreateMapping(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMapping", reflect.TypeOf((*MockAwsDnsClient)(nil).CreateMapping), arg0, arg1, arg2, arg3)
}
