// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/solo-io/valet/pkg/client/aws (interfaces: DnsClient)

// Package mock_aws is a generated GoMock package.
package mock_aws

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockDnsClient is a mock of DnsClient interface
type MockDnsClient struct {
	ctrl     *gomock.Controller
	recorder *MockDnsClientMockRecorder
}

// MockDnsClientMockRecorder is the mock recorder for MockDnsClient
type MockDnsClientMockRecorder struct {
	mock *MockDnsClient
}

// NewMockDnsClient creates a new mock instance
func NewMockDnsClient(ctrl *gomock.Controller) *MockDnsClient {
	mock := &MockDnsClient{ctrl: ctrl}
	mock.recorder = &MockDnsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDnsClient) EXPECT() *MockDnsClientMockRecorder {
	return m.recorder
}

// CreateMapping mocks base method
func (m *MockDnsClient) CreateMapping(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMapping", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMapping indicates an expected call of CreateMapping
func (mr *MockDnsClientMockRecorder) CreateMapping(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMapping", reflect.TypeOf((*MockDnsClient)(nil).CreateMapping), arg0, arg1, arg2, arg3)
}
