cluster:
  type: gke
  gke:
    name: glooe-customer-cluster-1
    location: us-central1-a
    project: solo-test-236622
gloo:
  enterprise: true
workflows:
  - name: path-match
    steps:
    - apply: https://raw.githubusercontent.com/solo-io/solo-docs/master/gloo/docs/static/content/upstream.yaml
    - apply: https://raw.githubusercontent.com/solo-io/solo-docs/master/gloo/docs/gloo_routing/virtual_services/routes/matching_rules/path_matching/prefix_vs.yaml
    - curl:
        path: /posts/1
        status_code: 200
        host: foo
    - curl:
        path: /posts/1
        status_code: 404