steps:
  # Setup SSH
  # These are required before git
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=ci/id_rsa.enc
      - --plaintext-file=/root/.ssh/id_rsa
      - --location=global
      - --keyring=build
      - --key=build-key
    volumes:
      - name: 'ssh'
        path: /root/.ssh
    id: 'get-ssh-key'
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod 600 /root/.ssh/id_rsa
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/id_rsa
        EOF`
        mv ./ci/github_known_hosts /root/.ssh/known_hosts
        git config --global url."ssh://git@github.com/solo-io".insteadOf https://github.com/solo-io
    volumes:
      - name: 'ssh'
        path: /root/.ssh
    id: 'configure-git'
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/solo-io/valet']
    id: 'clone'
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args: ['-c', 'cd valet && git checkout $COMMIT_SHA && git describe --tags']